spring.application.name=kanban

spring.datasource.url=jdbc:postgresql://localhost:5432/kanban_db
spring.datasource.username=postgres
spring.datasource.password=060106

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true